[2024-01-01T09:35:48.042+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: snow_dag.fetch_incidents manual__2024-01-01T09:33:30.152316+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
