[2024-01-04T06:15:23.800+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snow_dag.is_snow_api_ready scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T06:15:23.820+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snow_dag.is_snow_api_ready scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T06:15:23.820+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-04T06:15:23.932+0000] {taskinstance.py:2192} INFO - Executing <Task(HttpSensor): is_snow_api_ready> on 2024-01-03 00:00:00+00:00
[2024-01-04T06:15:23.936+0000] {standard_task_runner.py:60} INFO - Started process 100 to run task
[2024-01-04T06:15:23.940+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'snow_dag', 'is_snow_api_ready', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/servicenow_dag.py', '--cfg-path', '/tmp/tmpq0p5jhbo']
[2024-01-04T06:15:23.943+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask is_snow_api_ready
[2024-01-04T06:15:24.083+0000] {task_command.py:423} INFO - Running <TaskInstance: snow_dag.is_snow_api_ready scheduled__2024-01-03T00:00:00+00:00 [running]> on host 48e8e5b29b13
[2024-01-04T06:15:24.344+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prady1900' AIRFLOW_CTX_DAG_ID='snow_dag' AIRFLOW_CTX_TASK_ID='is_snow_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-01-04T06:15:24.345+0000] {http.py:130} INFO - Poking: api/now/table/incident
[2024-01-04T06:15:24.365+0000] {base.py:83} INFO - Using connection ID 'snow_api_id' for task execution.
[2024-01-04T06:15:25.769+0000] {base.py:293} INFO - Success criteria met. Exiting.
[2024-01-04T06:15:25.778+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=snow_dag, task_id=is_snow_api_ready, execution_date=20240103T000000, start_date=20240104T061523, end_date=20240104T061525
[2024-01-04T06:15:25.921+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-04T06:15:25.963+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-01-04T13:40:41.242+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snow_dag.is_snow_api_ready scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T13:40:41.345+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snow_dag.is_snow_api_ready scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T13:40:41.345+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-04T13:40:42.264+0000] {taskinstance.py:2192} INFO - Executing <Task(HttpSensor): is_snow_api_ready> on 2024-01-03 00:00:00+00:00
[2024-01-04T13:40:42.283+0000] {standard_task_runner.py:60} INFO - Started process 479 to run task
[2024-01-04T13:40:42.287+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'snow_dag', 'is_snow_api_ready', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/servicenow_dag.py', '--cfg-path', '/tmp/tmptyl95xjm']
[2024-01-04T13:40:42.332+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask is_snow_api_ready
[2024-01-04T13:40:42.505+0000] {task_command.py:423} INFO - Running <TaskInstance: snow_dag.is_snow_api_ready scheduled__2024-01-03T00:00:00+00:00 [running]> on host 4a92eecc6669
[2024-01-04T13:40:42.699+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prady1900' AIRFLOW_CTX_DAG_ID='snow_dag' AIRFLOW_CTX_TASK_ID='is_snow_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-01-04T13:40:42.700+0000] {http.py:130} INFO - Poking: api/now/table/incident
[2024-01-04T13:40:42.729+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 263, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 245, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/sensors/http.py", line 148, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/sensors/http.py", line 132, in poke
    response = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 145, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 98, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snow_api_id` isn't defined
[2024-01-04T13:40:42.739+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=snow_dag, task_id=is_snow_api_ready, execution_date=20240103T000000, start_date=20240104T134041, end_date=20240104T134042
[2024-01-04T13:40:42.834+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task is_snow_api_ready (The conn_id `snow_api_id` isn't defined; 479)
[2024-01-04T13:40:42.866+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-04T13:40:42.972+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
