[2024-01-04T13:46:02.152+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: db_dg.insert_data_in_db scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T13:46:02.162+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: db_dg.insert_data_in_db scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T13:46:02.162+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-04T13:46:02.243+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): insert_data_in_db> on 2024-01-03 00:00:00+00:00
[2024-01-04T13:46:02.248+0000] {standard_task_runner.py:60} INFO - Started process 682 to run task
[2024-01-04T13:46:02.251+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'db_dg', 'insert_data_in_db', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/create_database_dag.py', '--cfg-path', '/tmp/tmp6l34vlub']
[2024-01-04T13:46:02.253+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask insert_data_in_db
[2024-01-04T13:46:02.382+0000] {task_command.py:423} INFO - Running <TaskInstance: db_dg.insert_data_in_db scheduled__2024-01-03T00:00:00+00:00 [running]> on host 4a92eecc6669
[2024-01-04T13:46:02.597+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prady1900' AIRFLOW_CTX_DAG_ID='db_dg' AIRFLOW_CTX_TASK_ID='insert_data_in_db' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-01-04T13:46:02.598+0000] {sql.py:276} INFO - Executing: 
    insert into incident_new (impact,number,severity,priority,assignment_group,resolve_time,category) VALUES 
    (1,'INC00001',3,2,'database',4332,'rdbms');
[2024-01-04T13:46:02.608+0000] {base.py:83} INFO - Using connection ID 'postgres_connect' for task execution.
[2024-01-04T13:46:02.683+0000] {base.py:83} INFO - Using connection ID 'postgres_connect' for task execution.
[2024-01-04T13:46:02.691+0000] {sql.py:432} INFO - Running statement: 
    insert into incident_new (impact,number,severity,priority,assignment_group,resolve_time,category) VALUES 
    (1,'INC00001',3,2,'database',4332,'rdbms');, parameters: None
[2024-01-04T13:46:02.704+0000] {sql.py:441} INFO - Rows affected: 1
[2024-01-04T13:46:02.714+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=db_dg, task_id=insert_data_in_db, execution_date=20240103T000000, start_date=20240104T134602, end_date=20240104T134602
[2024-01-04T13:46:02.826+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-04T13:46:02.846+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
