[2024-01-04T07:00:52.556+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: db_dg.create_post_DB manual__2024-01-04T07:00:44.090125+00:00 [queued]>
[2024-01-04T07:00:52.570+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: db_dg.create_post_DB manual__2024-01-04T07:00:44.090125+00:00 [queued]>
[2024-01-04T07:00:52.570+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-04T07:00:52.679+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_post_DB> on 2024-01-04 07:00:44.090125+00:00
[2024-01-04T07:00:52.684+0000] {standard_task_runner.py:60} INFO - Started process 367 to run task
[2024-01-04T07:00:52.686+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'db_dg', 'create_post_DB', 'manual__2024-01-04T07:00:44.090125+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/create_database_dag.py', '--cfg-path', '/tmp/tmpoy0z72mf']
[2024-01-04T07:00:52.688+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask create_post_DB
[2024-01-04T07:00:52.829+0000] {task_command.py:423} INFO - Running <TaskInstance: db_dg.create_post_DB manual__2024-01-04T07:00:44.090125+00:00 [running]> on host 34fb0f920c20
[2024-01-04T07:00:53.063+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prady1900' AIRFLOW_CTX_DAG_ID='db_dg' AIRFLOW_CTX_TASK_ID='create_post_DB' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T07:00:44.090125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-04T07:00:44.090125+00:00'
[2024-01-04T07:00:53.065+0000] {sql.py:276} INFO - Executing: 
create table if not exists incident_new(
    id integer primary_key,
    impact integer,
    number varchar(50)
)
[2024-01-04T07:00:53.082+0000] {base.py:83} INFO - Using connection ID 'postgres_connect' for task execution.
[2024-01-04T07:00:53.209+0000] {base.py:83} INFO - Using connection ID 'postgres_connect' for task execution.
[2024-01-04T07:00:53.245+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Name or service not known

[2024-01-04T07:00:53.257+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=db_dg, task_id=create_post_DB, execution_date=20240104T070044, start_date=20240104T070052, end_date=20240104T070053
[2024-01-04T07:00:53.406+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 61 for task create_post_DB (could not translate host name "host.docker.local" to address: Name or service not known
; 367)
[2024-01-04T07:00:53.462+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-04T07:00:53.481+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
